### ISSUE TITLE
Crash server (Conflict mods)

### ISSUE THREAD

**Issue by Sepera-okeq** [TonimatasDEV/PacketFixer#13]
Minecraft ver: 1.20.1 - Fabric

Log full: https://paste.ee/p/3XoBy

when two mods are enabled сrash server (connectivity + packetfixer)

**Comment by TonimatasDEV** [comment]
> Minecraft ver: 1.20.1 - Fabric
> 
> Log full: https://paste.ee/p/3XoBy
> 
> when two mods are enabled сrash server (connectivity + packetfixer)

Try deleting "xxlpackets 1.0.4-1.20.x-1.20.1"

**Comment by Sepera-okeq** [comment]
> > Minecraft ver: 1.20.1 - Fabric
> > Log full: https://paste.ee/p/3XoBy
> > when two mods are enabled сrash server (connectivity + packetfixer)
> 
> Try deleting "xxlpackets 1.0.4-1.20.x-1.20.1"

No.... Crash

Log: https://paste.ee/p/RTOPB
