### ISSUE TITLE
1.1.5 crashes

### ISSUE THREAD

**Issue by GRKTheGreat** [TonimatasDEV/PacketFixer#14]
Log : https://mclo.gs/N9imOTW

**Comment by TonimatasDEV** [comment]
**Fixed in 1.1.6**

https://legacy.curseforge.com/minecraft/mc-mods/packet-fixer/files
https://modrinth.com/mod/packet-fixer/versions

**Comment by TonimatasDEV** [comment]
> Log : https://mclo.gs/N9imOTW

**Fixed in 1.1.6**

https://legacy.curseforge.com/minecraft/mc-mods/packet-fixer/files
https://modrinth.com/mod/packet-fixer/versions
