### ISSUE TITLE
Error on 1.20.1 when trying to join friend with Essential

### ISSUE THREAD

**Issue by Daltaxy** [TonimatasDEV/PacketFixer#16]
Hello.
After updating today (1.1.6), my friend can't join me anymore, and the Essential support team redirected me here.
debug.log: 
[debug.log](https://github.com/TonimatasDEV/PacketFixer/files/12504598/debug.log)
debug.log of my friend trying to join: 
[debug (3).log](https://github.com/TonimatasDEV/PacketFixer/files/12504599/debug.3.log)
Apparently linekd to PacketFixer.

Additionally, could have no link but since the update, sometimes when I try to join my world it says something about f_xxxxxx (x being numbers) and "internal exception cannot read field because "player" is null
then it fixes itself and doesn't happen again. very odd...

Anyways, this is the error my friend gets when trying to join:
![image](https://github.com/TonimatasDEV/PacketFixer/assets/111076631/53708d33-cf08-4445-8be5-cc8356074761)

**Comment by TonimatasDEV** [comment]
> Hello. After updating today (1.1.6), my friend can't join me anymore, and the Essential support team redirected me here. debug.log: [debug.log](https://github.com/TonimatasDEV/PacketFixer/files/12504598/debug.log) debug.log of my friend trying to join: [debug (3).log](https://github.com/TonimatasDEV/PacketFixer/files/12504599/debug.3.log) Apparently linekd to PacketFixer.
> 
> Additionally, could have no link but since the update, sometimes when I try to join my world it says something about f_xxxxxx (x being numbers) and "internal exception cannot read field because "player" is null then it fixes itself and doesn't happen again. very odd...
> 
> Anyways, this is the error my friend gets when trying to join: ![image](https://user-images.githubusercontent.com/111076631/265225245-53708d33-cf08-4445-8be5-cc8356074761.png)

The problem is that you have Connectivity installed, Packet Fixer is so to speak an upgraded version of Connectivity fixing more problems. That makes it incompatible. Remove connectivity so your friend can play :)

**Comment by TonimatasDEV** [comment]
In the next version 1.1.7 I fixed this issue.

**Comment by TonimatasDEV** [comment]
> Hello. After updating today (1.1.6), my friend can't join me anymore, and the Essential support team redirected me here. debug.log: [debug.log](https://github.com/TonimatasDEV/PacketFixer/files/12504598/debug.log) debug.log of my friend trying to join: [debug (3).log](https://github.com/TonimatasDEV/PacketFixer/files/12504599/debug.3.log) Apparently linekd to PacketFixer.
> 
> Additionally, could have no link but since the update, sometimes when I try to join my world it says something about f_xxxxxx (x being numbers) and "internal exception cannot read field because "player" is null then it fixes itself and doesn't happen again. very odd...
> 
> Anyways, this is the error my friend gets when trying to join: ![image](https://user-images.githubusercontent.com/111076631/265225245-53708d33-cf08-4445-8be5-cc8356074761.png)

Fixed:
[PacketFixer-forge-1.1.7-1.20.1.zip](https://github.com/TonimatasDEV/PacketFixer/files/12504714/PacketFixer-forge-1.1.7-1.20.1.zip)

**Comment by Daltaxy** [comment]
> > Hello. After updating today (1.1.6), my friend can't join me anymore, and the Essential support team redirected me here. debug.log: [debug.log](https://github.com/TonimatasDEV/PacketFixer/files/12504598/debug.log) debug.log of my friend trying to join: [debug (3).log](https://github.com/TonimatasDEV/PacketFixer/files/12504599/debug.3.log) Apparently linekd to PacketFixer.
> > Additionally, could have no link but since the update, sometimes when I try to join my world it says something about f_xxxxxx (x being numbers) and "internal exception cannot read field because "player" is null then it fixes itself and doesn't happen again. very odd...
> > Anyways, this is the error my friend gets when trying to join: ![image](https://user-images.githubusercontent.com/111076631/265225245-53708d33-cf08-4445-8be5-cc8356074761.png)
> 
> Fixed: (The mod is in the Zip file) [PacketFixer-forge-1.1.7-1.20.1.zip](https://github.com/TonimatasDEV/PacketFixer/files/12504714/PacketFixer-forge-1.1.7-1.20.1.zip)

thanks! do I remove Connectivity as well? I don't mind removing it if this does the same thing anyways

**Comment by TonimatasDEV** [comment]
> > > Hello. After updating today (1.1.6), my friend can't join me anymore, and the Essential support team redirected me here. debug.log: [debug.log](https://github.com/TonimatasDEV/PacketFixer/files/12504598/debug.log) debug.log of my friend trying to join: [debug (3).log](https://github.com/TonimatasDEV/PacketFixer/files/12504599/debug.3.log) Apparently linekd to PacketFixer.
> > > Additionally, could have no link but since the update, sometimes when I try to join my world it says something about f_xxxxxx (x being numbers) and "internal exception cannot read field because "player" is null then it fixes itself and doesn't happen again. very odd...
> > > Anyways, this is the error my friend gets when trying to join: ![image](https://user-images.githubusercontent.com/111076631/265225245-53708d33-cf08-4445-8be5-cc8356074761.png)
> > 
> > 
> > Fixed: (The mod is in the Zip file) [PacketFixer-forge-1.1.7-1.20.1.zip](https://github.com/TonimatasDEV/PacketFixer/files/12504714/PacketFixer-forge-1.1.7-1.20.1.zip)
> 
> thanks! do I remove Connectivity as well? I don't mind removing it if this does the same thing anyways

If it works fine, don't touch anything, if it keeps giving you problems, you should remove it. I have already reported the error to Conne

**Comment by Daltaxy** [comment]
> > > > Hello. After updating today (1.1.6), my friend can't join me anymore, and the Essential support team redirected me here. debug.log: [debug.log](https://github.com/TonimatasDEV/PacketFixer/files/12504598/debug.log) debug.log of my friend trying to join: [debug (3).log](https://github.com/TonimatasDEV/PacketFixer/files/12504599/debug.3.log) Apparently linekd to PacketFixer.
> > > > Additionally, could have no link but since the update, sometimes when I try to join my world it says something about f_xxxxxx (x being numbers) and "internal exception cannot read field because "player" is null then it fixes itself and doesn't happen again. very odd...
> > > > Anyways, this is the error my friend gets when trying to join: ![image](https://user-images.githubusercontent.com/111076631/265225245-53708d33-cf08-4445-8be5-cc8356074761.png)
> > > 
> > > 
> > > Fixed: (The mod is in the Zip file) [PacketFixer-forge-1.1.7-1.20.1.zip](https://github.com/TonimatasDEV/PacketFixer/files/12504714/PacketFixer-forge-1.1.7-1.20.1.zip)
> > 
> > 
> > thanks! do I remove Connectivity as well? I don't mind removing it if this does the same thing anyways
> 
> If it works fine, don't touch anything, if it keeps giving you problems, you should remove it. I have already reported the error to Conne

that update fixed it! thank you :)
my friend did get a similar issue to this once but again, it's random so retrying worked instantly.
thanks again :)
![image](https://github.com/TonimatasDEV/PacketFixer/assets/111076631/bf712c6a-1aea-471e-839c-af538d100c03)
