### ISSUE TITLE
v1.1.5 crashes 1.19.2 client and 1.19.2 server

### ISSUE THREAD

**Issue by allanonmage** [TonimatasDEV/PacketFixer#17]
Server log
[latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12504756/latest.log)

Client log
[latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12504759/latest.log)

**Comment by TonimatasDEV** [comment]
> Server log [latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12504756/latest.log)
> 
> Client log [latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12504759/latest.log)

Please, download the latest version.

**Comment by allanonmage** [comment]
It was the latest on Modrinth when I downloaded it, and it was like 2 or 5 hours old according to Modrinth.  I went back one version and it seems to be running fine.

**Comment by TonimatasDEV** [comment]
> It was the latest on Modrinth when I downloaded it, and it was like 2 or 5 hours old according to Modrinth. I went back one version and it seems to be running fine.

If it works fine, do not touch anything, if it continues to give you problems, you should remove it.

**Comment by TonimatasDEV** [comment]
> It was the latest on Modrinth when I downloaded it, and it was like 2 or 5 hours old according to Modrinth. I went back one version and it seems to be running fine.

The last version is the 1.1.6
![image](https://github.com/TonimatasDEV/PacketFixer/assets/79017964/b0767de6-326f-4da3-a40b-e93a012fddb4)
