### ISSUE TITLE
Crash on 1.20.1

### ISSUE THREAD

**Issue by Fleepe** [TonimatasDEV/PacketFixer#18]
After adding your mod to my modpack the game crashes.
Everything is updated: Windows 10 (22H2), Adoptium Java 17 (17.0.8.7) for 1.20.1 and all mods are updated too.

[crash-2023-09-03_18.18.29-client.txt](https://github.com/TonimatasDEV/PacketFixer/files/12506401/crash-2023-09-03_18.18.29-client.txt)
[latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12506402/latest.log)

**Comment by TonimatasDEV** [comment]
> After adding your mod to my modpack the game crashes. Everything is updated: Windows 10 (22H2), Adoptium Java 17 (17.0.8.7) for 1.20.1 and all mods are updated too.
> 
> [crash-2023-09-03_18.18.29-client.txt](https://github.com/TonimatasDEV/PacketFixer/files/12506401/crash-2023-09-03_18.18.29-client.txt) [latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12506402/latest.log)

You have Packet Fixer 1.1.6

**Comment by Fleepe** [comment]
Still.
[crash-2023-09-03_18.55.59-client.txt](https://github.com/TonimatasDEV/PacketFixer/files/12506503/crash-2023-09-03_18.55.59-client.txt)
[latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12506508/latest.log)

**Comment by TonimatasDEV** [comment]
> @TonimatasDEV Still. [crash-2023-09-03_18.55.59-client.txt](https://github.com/TonimatasDEV/PacketFixer/files/12506503/crash-2023-09-03_18.55.59-client.txt) [latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12506508/latest.log)

This is caused by meteor client

**Comment by Fleepe** [comment]
Understood, thank you

**Comment by TonimatasDEV** [comment]
> Understood, thank you

Here is Meteor's link to report it. Thanks for report.
https://github.com/MeteorDevelopment/meteor-client/issues
