### ISSUE TITLE
Wrong version tagged to curseforge.

### ISSUE THREAD

**Issue by Darkmega18** [TonimatasDEV/PacketFixer#20]
latest update for the mod says it's for fabric. instead of forge. please tag it properly so my pack stops prompting me to download a version of a mod I can't even use. _(which also resulted in my friends being unable to join me for a bit until I realized. since I need this mod to fix that giant packet bug it patches)_

**Comment by TonimatasDEV** [comment]
> latest update for the mod says it's for fabric. instead of forge. please tag it properly so my pack stops prompting me to download a version of a mod I can't even use. _(which also resulted in my friends being unable to join me for a bit until I realized. since I need this mod to fix that giant packet bug it patches)_

What version?

**Comment by Darkmega18** [comment]
1.19.2 forge.
but it's displaying the latest as a 1.19.2 for fabric version.

Both are 1.1.6 of packet fixer.

**Comment by TonimatasDEV** [comment]
> 1.19.2 forge.
> but it's displaying the latest as a 1.19.2 for fabric version.
> 
> Both are 1.1.6 of packet fixer.

Fixed, thanks you very much.
