### ISSUE TITLE
[SUGGESTION] A fix for this error

### ISSUE THREAD

**Issue by Sunconure11** [TonimatasDEV/PacketFixer#21]
![image](https://github.com/TonimatasDEV/PacketFixer/assets/5614902/f75fea21-7b85-4ccc-b6c8-d76cc9e2ad5b)

I cannot seem to enter a server because of it, and I believe it is packet related.
[latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12569194/latest.log)

**Comment by TonimatasDEV** [comment]
> I cannot seem to enter a server because of it, and I believe it is packet related.

I will take a closer look, I have never seen this error before.

**Comment by Sunconure11** [comment]
It's supposedly very common, and seems to be triggered by many things. I even found reports of it on Spigot forks. Simply googling the error results in reports of this as far back as 2016. I have also tasked ModernFix with looking into this, as well, in the event this can't be done here.

**Comment by TonimatasDEV** [comment]
> It's supposedly very common, and seems to be triggered by many things. I even found reports of it on Spigot forks. Simply googling the error results in reports of this as far back as 2016. I have also tasked ModernFix with looking into this, as well, in the event this can't be done here.

In order to reproduce the error, could you send me the list of mods, if it is not too much trouble?

**Comment by TonimatasDEV** [comment]
> It's supposedly very common, and seems to be triggered by many things. I even found reports of it on Spigot forks. Simply googling the error results in reports of this as far back as 2016. I have also tasked ModernFix with looking into this, as well, in the event this can't be done here.

Test this version:
[PacketFixer-fabric-1.1.8-dev-1.20.1.zip](https://github.com/TonimatasDEV/PacketFixer/files/12569460/PacketFixer-fabric-1.1.8-dev-1.20.1.zip)

**Comment by TonimatasDEV** [comment]
> It's supposedly very common, and seems to be triggered by many things. I even found reports of it on Spigot forks. Simply googling the error results in reports of this as far back as 2016. I have also tasked ModernFix with looking into this, as well, in the event this can't be done here.

Test this version:
[PacketFixer-fabric-1.1.8-dev-1.19.2.zip](https://github.com/TonimatasDEV/PacketFixer/files/12569491/PacketFixer-fabric-1.1.8-dev-1.19.2.zip)

**Comment by Sunconure11** [comment]
Mod list is in the log.

Gonna test your build.

**Comment by Sunconure11** [comment]
![image](https://github.com/TonimatasDEV/PacketFixer/assets/5614902/3cbc555d-e79f-49d6-a7d3-1a59832deb46)

**Comment by Sunconure11** [comment]
[latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12569539/latest.log)

**Comment by TonimatasDEV** [comment]
> ![image](https://user-images.githubusercontent.com/5614902/266857223-3cbc555d-e79f-49d6-a7d3-1a59832deb46.png)

Test this version:
[PacketFixer-fabric-1.1.8-dev.build2-1.19.2.zip](https://github.com/TonimatasDEV/PacketFixer/files/12569690/PacketFixer-fabric-1.1.8-dev.build2-1.19.2.zip)

**Comment by Sunconure11** [comment]
![image](https://github.com/TonimatasDEV/PacketFixer/assets/5614902/18668ad1-9a15-4c64-b5f5-0fdc3b91add3)

**Comment by Sunconure11** [comment]
[latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12569747/latest.log)

**Comment by Sunconure11** [comment]
https://github.com/astei/krypton

**Comment by TonimatasDEV** [comment]
> https://github.com/astei/krypton

Test this version:
[PacketFixer-fabric-1.1.8-dev.build3-1.19.2.zip](https://github.com/TonimatasDEV/PacketFixer/files/12569776/PacketFixer-fabric-1.1.8-dev.build3-1.19.2.zip)

**Comment by Sunconure11** [comment]
![image](https://github.com/TonimatasDEV/PacketFixer/assets/5614902/6fff9a87-45cc-4453-98f5-8e66fdb87c95)

[latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12569806/latest.log)

![image](https://media.tenor.com/OIlqexx5iIMAAAAC/squidward-register.gif)

**Comment by Sunconure11** [comment]
Gonna test without Krypton and see what happens. Looking at how the dev acts towards some has convinced me to at least try that idea.

**Comment by TonimatasDEV** [comment]
> Gonna test without Krypton and see what happens. Looking at how the dev acts towards some has convinced me to at least try that idea.

Let's see if it works

**Comment by Sunconure11** [comment]
![image](https://github.com/TonimatasDEV/PacketFixer/assets/5614902/ef4f16e1-e2e1-45cd-8438-78787eb7b94d)

![image](https://github.com/TonimatasDEV/PacketFixer/assets/5614902/a781f94a-ac10-47d0-8765-82691244e061)

**Comment by Sunconure11** [comment]
[latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12569866/latest.log)

**Comment by TonimatasDEV** [comment]
> ![image](https://user-images.githubusercontent.com/5614902/266860341-ef4f16e1-e2e1-45cd-8438-78787eb7b94d.png)
> 
> ![image](https://user-images.githubusercontent.com/5614902/266860372-a781f94a-ac10-47d0-8765-82691244e061.png)

Test this version:
[PacketFixer-fabric-1.1.8-dev.build4-1.19.2.zip](https://github.com/TonimatasDEV/PacketFixer/files/12569890/PacketFixer-fabric-1.1.8-dev.build4-1.19.2.zip)

**Comment by Sunconure11** [comment]
![image](https://github.com/TonimatasDEV/PacketFixer/assets/5614902/1098fbcd-a476-4a92-88a6-94691fdae8cc)
[latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12569915/latest.log)

**Comment by Sunconure11** [comment]
https://bugs.mojang.com/browse/MC-95529

**Comment by TonimatasDEV** [comment]
> ![image](https://user-images.githubusercontent.com/5614902/266861279-1098fbcd-a476-4a92-88a6-94691fdae8cc.png) [latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12569915/latest.log)

I have tried, but I think it is not fixable, you can try to use Packet Fixer version 1.1.7 without Krypton. Thank you very much for reporting the problem.

**Comment by TonimatasDEV** [comment]
> https://bugs.mojang.com/browse/MC-95529

I recommend that you remove all mods and add them little by little to see which ones give the problem.

**Comment by Sunconure11** [comment]
I'd suggest at least putting some of these fixes in the next build of your mod, for the public to use, just in case they help someone else.

**Comment by Sunconure11** [comment]
I think I know my issue, and am going to try and get some people to help me with such.

**Comment by Linguardium** [comment]
iirc, Forge implemented a packet splitter specifically for these issues. basically splitting vanilla packets into multiple packets then combining again on client since there are at least 3 different vanilla packets that send an unlimited list (which breaks the varint barrier)

**Comment by Sunconure11** [comment]
@TonimatasDEV 

You might want to look at this.

**Comment by Linguardium** [comment]
https://github.com/FabricMC/fabric/pull/2525 this might be useful too. The approach is effectively the same, but the execution would have to be tweaked to not be as invasive. There have been some nice updates to the networking API in FAPI though so it should be possible now
