### ISSUE TITLE
Possible solution for #21

### ISSUE THREAD

**Issue by Sunconure11** [TonimatasDEV/PacketFixer#22]
https://github.com/TonimatasDEV/PacketFixer/issues/21#issuecomment-1716807706

You should probably check this out.

**Comment by qyl27** [comment]
It seems that it will cause this mod required in both client and server?

**Comment by TonimatasDEV** [comment]
> It seems that it will cause this mod required in both client and server?

It is simply pinned, it will not be done for the time being.

**Comment by Sunconure11** [comment]
Do you have any idea as to when you'd be free to do this? I know I normally shouldn't ask this, but given the nature of this solution, it would probably help quite a few people.

**Comment by Sunconure11** [comment]
@Linguardium Maybe you can help with getting this on various versions of the mod?

**Comment by Sunconure11** [comment]
I discovered this in 1.19.2 though, so I'd say 1.19.2 and up should receive this.

**Comment by TonimatasDEV** [comment]
> Do you have any idea as to when you'd be free to do this? I know I normally shouldn't ask this, but given the nature of this solution, it would probably help quite a few people.

The creators of Forge and Fabric said they were not going to do it because they don't think it is the most optimal way. If a case will create a separate mod.

**Comment by TonimatasDEV** [comment]
@Sunconure11 Test this version:
[PacketFixer-fabric-1.1.8-1.19.2.test20.zip](https://github.com/TonimatasDEV/PacketFixer/files/12640564/PacketFixer-fabric-1.1.8-1.19.2.test20.zip)

**Comment by Sunconure11** [comment]
I will shortly. It looks like a mod had a bad update or something for me currently.

**Comment by Sunconure11** [comment]
I'll get back with you in a little while. I also woke up a bit... too early, and I also still haven't found why I'm having an unrelated issue.

**Comment by Sunconure11** [comment]
Alright, it looks like I can begin bug hunting now

**Comment by TonimatasDEV** [comment]
> Alright, it looks like I can begin bug hunting now

Let me know if I have managed to solve the problem you had last time.

**Comment by Sunconure11** [comment]
https://gist.github.com/Sunconure11/fbd57261851d30552685e64655cdfa7e

**Comment by TonimatasDEV** [comment]
> https://gist.github.com/Sunconure11/fbd57261851d30552685e64655cdfa7e

What is the problem?

**Comment by Sunconure11** [comment]
Packet splitter mixin seems to be failing.

https://pastebin.com/g8hhAEzX

**Comment by Sunconure11** [comment]
If you find a possible cause, I'll test it again, but I need to lay down for a bit.

**Comment by TonimatasDEV** [comment]
> Packet splitter mixin seems to be failing.
> 
> https://pastebin.com/g8hhAEzX

Test this version:
[PacketFixer-fabric-1.1.8-1.19.2.test21.zip](https://github.com/TonimatasDEV/PacketFixer/files/12640939/PacketFixer-fabric-1.1.8-1.19.2.test21.zip)

**Comment by Sunconure11** [comment]
Looks like the server is now hitting something that is more likely related to the host themselves. I'll see what can be done there.

**Comment by Sunconure11** [comment]
```
16.09 19:53:37 [Server] Netty Epoll Server IO #5/WARN java.lang.OutOfMemoryError: Requested array size exceeds VM limit
16.09 19:53:37 [Server] Netty Epoll Server IO #5/WARN Network error for:packet_handler
16.09 19:53:37 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
16.09 19:53:37 [Server] Netty Epoll Server IO #5/ERROR Twilight Forest: Exception occurred in netty pipeline
16.09 19:53:37 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
16.09 19:53:37 [Server] Netty Epoll Server IO #5/ERROR Exception occurred in netty pipeline
16.09 19:53:37 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
16.09 19:53:37 [Server] Netty Epoll Server IO #5/WARN java.lang.OutOfMemoryError: Requested array size exceeds VM limit
16.09 19:53:37 [Server] Netty Epoll Server IO #5/WARN Network error for:packet_handler
16.09 19:53:37 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
```

**Comment by Sunconure11** [comment]
Server uses 16 gigs, but it is apparently running into this when it is not even using that much RAM.

**Comment by Sunconure11** [comment]
I have posted it here just in case it is being a bit deceptive and that is not host related.

**Comment by Sunconure11** [comment]
I decided to do some digging, by running the server and client without Packet Fixer.

https://pastebin.com/nGyHBF3i

https://pastebin.com/TtZNF6F5

**Comment by Sunconure11** [comment]
I am also using these mods, in case they may have recipe conflicts:

https://www.curseforge.com/minecraft/mc-mods/block-swap

https://www.curseforge.com/minecraft/mc-mods/almost-unified

https://www.curseforge.com/minecraft/mc-mods/recipe-essentials-forge-fabric

**Comment by TonimatasDEV** [comment]
> Server uses 16 gigs, but it is apparently running into this when it is not even using that much RAM.

Better not to fix this problem, as it causes the servers to consume all your ram. That's why it has these limits. Thank you very much for reporting this bug.

**Comment by Sunconure11** [comment]
Just curious, but do alternate solutions exist that don't eat up so much memory?

**Comment by Sunconure11** [comment]
Or at least, are physically possible?

**Comment by TonimatasDEV** [comment]
> Or at least, are physically possible?

They may be possible, but I have not seen them exist.

**Comment by TonimatasDEV** [comment]
@Sunconure11 I have a plan for fix this

**Comment by Sunconure11** [comment]
Of note is that this mod still has some oddities with Krypton installed, and with all of these tests, I had to uninstall Krypton. I suggest adding some compat there too.

**Comment by Linguardium** [comment]
> Just curious, but do alternate solutions exist that don't eat up so much memory?

Forge already has the fix for it built into forge itself. this would really only be needed for Fabric.

**Comment by Sunconure11** [comment]
I'm mostly on Quilt because there are a few things exclusive to it that I wanted to play with.

**Comment by TonimatasDEV** [comment]
> Just curious, but do alternate solutions exist that don't eat up so much memory?
Test this version:
[PacketFixer-fabric-1.1.8-1.19.2.test3246178234.zip](https://github.com/TonimatasDEV/PacketFixer/files/12641729/PacketFixer-fabric-1.1.8-1.19.2.test3246178234.zip)

**Comment by Sunconure11** [comment]
Will have to get to it tomorrow. Am in bed.

**Comment by Sunconure11** [comment]
Prepping to test now.

**Comment by Sunconure11** [comment]
Also, regardless of my results, could you check these two mods for any possible incompat issues for the possible solution?

https://www.curseforge.com/minecraft/mc-mods/connectivity

https://www.curseforge.com/minecraft/mc-mods/krypton

**Comment by Sunconure11** [comment]
Hm, we may be close. I can enter, but the TPS seems to be very low, so stuff takes forever to load up on my end. It is possible pregeneration may be needed at this point, but I'll see how a restart of the server handles things first.

**Comment by Sunconure11** [comment]
No visible errors in the log, aside from can't keep up ones. Gonna try some ideas in the mean time.

**Comment by Sunconure11** [comment]
Tried to test with Very Many Players to see if I could load in fully, but I just got stuck at the loading screen for the server. Gonna see if Krypton has issues with these changes next. Will take pictures and logs of both issues. But it seems we are getting close.

**Comment by Sunconure11** [comment]
https://pastebin.com/qd5Rc745

Looks like the packet splitter mixin fails with Krypton.

**Comment by Sunconure11** [comment]
![image](https://github.com/TonimatasDEV/PacketFixer/assets/5614902/e7c66587-4e71-47b8-85ee-c6a1192fec1d)

VMP gets stuck on loading terrain. There was one last issue, lemme recreate it.

**Comment by Sunconure11** [comment]
https://legacy.curseforge.com/members/someaddon/projects

Some of the chunk-related mods may need a look over in regards to compat with VMP and this.

**Comment by Sunconure11** [comment]
Going to recreate the final issue now

**Comment by Sunconure11** [comment]
Okay, so it seems the VMP issue occurs not because of VMP, but due to the map itself. It does not want to load in.

**Comment by Sunconure11** [comment]
[latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12643200/latest.log)
Server log

**Comment by Sunconure11** [comment]
[latest.log](https://github.com/TonimatasDEV/PacketFixer/files/12643206/latest.log)
Client log

**Comment by Sunconure11** [comment]
I'm seeing a mixin failure in the log with this...

https://www.curseforge.com/minecraft/mc-mods/better-chunk-loading-forge-fabric

**Comment by Sunconure11** [comment]
If I find any more info, I will post it. But I do not seem to know of anything, aside from maybe some kind of issue with the chunk performance mods

**Comment by Sunconure11** [comment]
@Linguardium @TonimatasDEV Maybe compare the Forge solution to the one being attempted? Maybe they solved weird issues like this.

**Comment by TonimatasDEV** [comment]
> Also, regardless of my results, could you check these two mods for any possible incompat issues for the possible solution?

Connectivity is full compatible

**Comment by TonimatasDEV** [comment]
> https://pastebin.com/qd5Rc745
> 
> Looks like the packet splitter mixin fails with Krypton.

Delete Krypton

**Comment by TonimatasDEV** [comment]
@Sunconure11 Does it let you login to the server?  Is the TPS problem caused by Packet Fixer or by the number of mods?

**Comment by Sunconure11** [comment]
It shows me logged in on the log... but I am not physically in game.

TPS could be mods, yes, but I want to see what is going on a bit more. I am planning on further clean up of this pack, but I've been unable to find someone willing to help me, or has the time to.

**Comment by Sunconure11** [comment]
Cleanup is a bit hard here too, given a lot of the config stuff I did, and what not.

**Comment by TonimatasDEV** [comment]
> It shows me logged in on the log... but I am not physically in game.
> 
> TPS could be mods, yes, but I want to see what is going on a bit more. I am planning on further cleanup of this pack, but I've been unable to find someone willing to help me, or has the time to.

A modpack of 831 mods is too big, you would need a very very powerful server, how many cores and ram do you have in the server?

**Comment by Sunconure11** [comment]
https://apexminecrafthosting.com/pricing/?game=minecraft

Using the EX Series plan.

**Comment by Sunconure11** [comment]
My PC may be more powerful, but I'd rather wait until I have something like a 5950 for running any servers from my machine, so that I have more cores and threads free.

**Comment by Sunconure11** [comment]
I might have found someone to help with clean up. If, after this effort, this still happens, I'll come here. I will hold onto a build of Packet Fix created here just until then, just in case any issues pop up in singleplayer while working on this

**Comment by Sunconure11** [comment]
Also, this issue first came up while testing, but just to make sure of something, but is this my GPU going bad, or something else?

I am starting on some cleanup of the pack, up until I can get it to a point where I can enter fully and load a world, 

![image](https://github.com/TonimatasDEV/PacketFixer/assets/5614902/99184dce-7c37-4290-abfd-abb9676ff49f)

**Comment by Sunconure11** [comment]
Hm... I have a suspect mod, but I don't know for certain. However, I am calling it suspect due to it's nature.

https://github.com/MehVahdJukaar/WoodGood

**Comment by Sunconure11** [comment]
My reason for thinking it could be suspect is due to the sheer amount of recipes it could end up adding in the right situations.

**Comment by Sunconure11** [comment]
@embeddt

You wanna take this over?

Also, would it be possible to make a version of the packet splitter mixin that is compatible with Krypton?

**Comment by embeddedt** [comment]
Not sure what I'm expected to see/do here.

**Comment by Sunconure11** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/7485

https://github.com/FabricMC/fabric/pull/2525

There were two, separate ideas of the same thing, in these pulls. A packet splitter, basically.

**Comment by embeddedt** [comment]
Doesn't Connectivity already solve this issue by bumping the maximum packet size?

**Comment by Sunconure11** [comment]
I had also did quite a bit of testing to see if my issue was packet-related or mod-count related. Still working on trimming the mod count.

And it seems in some cases, it does not fully solve the issue, if this issue is packet-related.

**Comment by TonimatasDEV** [comment]
> Doesn't Connectivity already solve this issue by bumping the maximum packet size?

Connectivity is really just a monitor, it only fixes 3-packet size, phantom blocks, improves errors and gives you information about packet usage. Connectivity does nothing else.

**Comment by Sunconure11** [comment]
> Doesn't Connectivity already solve this issue by bumping the maximum packet size?

Looks like according to @TonimatasDEV, it does not really. @embeddedt

**Comment by TonimatasDEV** [comment]
@Sunconure11 The version I passed you does not work?

**Comment by Sunconure11** [comment]
> @Sunconure11 The version I passed you does not work?

It works, but I was referring to Embed.

**Comment by Sunconure11** [comment]
Well, I still can't load into a server fully, as it just stalls in a ghost world, best way to describe it, despite the console saying I'm in.

**Comment by Sunconure11** [comment]
Singleplayer still runs fine.

**Comment by Sunconure11** [comment]
While hunting for people to aid me with my pack, someone pointed out this issue to me, and given I have both mods… maybe there’s something here that can be done? https://github.com/terrarium-earth/Chipped/issues/214

**Comment by Sunconure11** [comment]
Hm, are there any limits on the packet splitter? Just asking while I pursue a few possible leads.
