### ISSUE TITLE
[1.20.1] [Fabric] Cant fit X into 3 error when joining a server

### ISSUE THREAD

**Issue by sirben99** [TonimatasDEV/PacketFixer#23]
Hey!

I have an issue where when i try to join a server, i get an issue where X number cant fit to 3 in a modpack.  I assume this is something to do with packets? I saw that someone else also had this issue, but this is for a different version (1.20.1). 

Ive been trying to solve this for 5 days now, and im going insane. I noticed mention that Krypton should be deleted, but no dice. Same with Chipped and Wood Good (Deleted Wood Good, no dice). I have tried to binary the modpack for days but nothing useful has come up. I do have ALOT of mods (~500), but even when shrink to mere ~300-250, the issue is still there.

Any help with the issue would be greatly appreciated. 

Log of the error (Full log is too big for PasteBin) https://pastebin.com/RVXSCttW

PacketFixes version: 1.1.7-Fabric

**Comment by TonimatasDEV** [comment]
> n a modpack. I assume this is something to do with packets? I saw that someone else also had this issue, but this is for a different version (1.20.1).
> 
> Ive been trying to solve this for 5 days now, and

This problem is an internal fabric problem that forge does not have. You can try to install Krypton together with packet fixer but this problem may not be solved externally (with mods).

**Comment by sirben99** [comment]
I have decided to [report this](https://github.com/FabricMC/fabric/issues/3382) to the Fabric them self, since its an internal issue. Thank you for the explanation!

**Comment by Luke100000** [comment]
Hi, found and fixed the error:

https://github.com/TonimatasDEV/PacketFixer/compare/master...Luke100000:PacketFixer:SplitterFix

The maximum size for a frame was still 3 bytes, too small for bigger packets. I do not know if the fix is the best way to do so but it solves the issue for now.

I see no relation to Fabric.

The fix is incompatible with Krypton and applied to 1.20.1.

**Comment by TonimatasDEV** [comment]
> Hi, found and fixed the error:
> 
> [master...Luke100000:PacketFixer:SplitterFix](https://github.com/TonimatasDEV/PacketFixer/compare/master...Luke100000:PacketFixer:SplitterFix)
> 
> The maximum size for a frame was still 3 bytes, too small for bigger packets. I do not know if the fix is the best way to do so but it solves the issue for now.
> 
> I see no relation to Fabric.
> 
> The fix is incompatible with Krypton and applied to 1.20.1.

It is true that it is not a manufacturing problem, actually making the limit higher can be solved. Temporarily it is possible to do what I have to investigate to do it in a better way.

**Comment by Zendrex** [comment]
Also getting this error in the forge version of the mod while running ATM9 0.2.10 (latest release as of day). As a caveat, I am running the server within Mohist (as well as ProxyCompatibleForge) and behind a Velocity proxy so there are a number of other things that may cause this too.

**Comment by Zendrex** [comment]
I'm aware of a solution that resolve this (and negates the purpose of this mod) named [Ambassador](https://modrinth.com/plugin/ambassador), however it messes with the network stack so much that it causes issues with LuckPerms and other related plugins. From discussion within the Mohist discord server, the general consensus is to NOT use Ambassador if it can be helped, however as of right now, its the only solution which allows the modpack (and honestly most large modpacks) to run behind a Velocity proxy.

If the fix provided by https://github.com/TonimatasDEV/PacketFixer/issues/23#issuecomment-1768309401 is available to test, I'll gladly give it a shot and report back. Unsure if 1.1.7 includes said fix, however if it is and it's still not working, I'll look further into if its a Velocity issue.

**Comment by TonimatasDEV** [comment]
**Fixed.** Download the latest version in Modrinth or CurseForge
