### ISSUE TITLE
Still have Payload may not be larger than 1048576 bytes when trying to join my server 1.20.1 Fabric

### ISSUE THREAD

**Issue by thatkidjustinn** [TonimatasDEV/PacketFixer#29]
Me and my friends put together a modpack for 1.20.1 fabric and at first it kept kicking us from the server with the "Payload may not be larger than 1048576 bytes" error. We found packet fixer and put it on the server and the modpack because we thought it would help, but we still can't get on the server and when it kicks us off the server it still says "Payload may not be larger than 1048576 bytes". 

[latest.log](https://github.com/TonimatasDEV/PacketFixer/files/14154437/latest.log)

**Comment by TonimatasDEV** [comment]
@thatkidjustinn You put the mod in the client and server or only on server?

**Comment by TonimatasDEV** [comment]
Fixed in the latest version

**Comment by Lord-drageon** [comment]
encountering this problem in all versions for 1.19.2, can you backpatch this to 1.19.2? do you need modlist for testing?

**Comment by TonimatasDEV** [comment]
> encountering this problem in all versions for 1.19.2, can you backpatch this to 1.19.2? do you need modlist for testing?

Have you the mod in client/server side?
