### ISSUE TITLE
Crash on both server and client 1.20.1-1.2.4

### ISSUE THREAD

**Issue by Pop000100** [TonimatasDEV/PacketFixer#30]
[latest.log](https://github.com/TonimatasDEV/PacketFixer/files/14231781/latest.log)
looks like a conflict with ferrite core. In the statement compatibility

**Comment by TonimatasDEV** [comment]
> [latest.log](https://github.com/TonimatasDEV/PacketFixer/files/14231781/latest.log) looks like a conflict with ferrite core. In the statement compatibility

Fixed in the latest version of Fabric (1.2.5). You can download it in Modrinth, foir CurseForge wait 20 minutes.
