### ISSUE TITLE
NBT tag too large not resolved

### ISSUE THREAD

**Issue by AndreaSciscioli** [TonimatasDEV/PacketFixer#33]
NBT tag too large errors occured also while having this mod installed in my server. Is a common mod? An only client mod? Or works also on servers? Actually didn't resolved my problem and i don t know what to do

**Comment by TonimatasDEV** [comment]
> NBT tag too large errors occured also while having this mod installed in my server. Is a common mod? An only client mod? Or works also on servers? Actually didn't resolved my problem and i don t know what to do

You need the mod in both sides

**Comment by TonimatasDEV** [comment]
@AndreaSciscioli
