### ISSUE TITLE
[1.16.5] Cannot join (singleplayer) worlds

### ISSUE THREAD

**Issue by cata023** [TonimatasDEV/PacketFixer#37]
![image](https://github.com/TonimatasDEV/PacketFixer/assets/19790426/db2d9ce3-9bf1-4805-8d05-74ebd88b8bf1)
The world join screen freezes here. In the logs, this error pops up:
`[22:39:31] [Server thread/INFO] [minecraft/ServerLoginNetHandler]: com.mojang.authlib.GameProfile@499d65ad[id=67db8d36-ac6c-494f-b0d3-26a0caaa7e27,name=Cata023,properties={textures=[com.mojang.authlib.properties.Property@1cdc8d1d]},legacy=false] (local:E:45ab4d52) lost connection: Internal Exception: java.lang.ClassCastException: net.minecraft.network.login.ServerLoginNetHandler cannot be cast to net.minecraft.client.network.play.IClientPlayNetHandler`

**Comment by TonimatasDEV** [comment]
@cata023 Forge or fabric?

**Comment by cata023** [comment]
Forge
