### ISSUE TITLE
Crash on launch (1.4.0)- "Error loading companion plugin class for mixin config"

### ISSUE THREAD

**Issue by DaAstronautical** [TonimatasDEV/PacketFixer#39]
(Mirrored from my entry on the Discord forum thread: "Fabric 1.20.1 instant crash")

The client crashes on launch with the following error:

```
[26May2024 10:42:30.882] [main/ERROR] [mixin/]: Error loading companion plugin class [dev.tonimatas.packetfixer.mixins.MixinConfigPlugin] for mixin config [packetfixer-common.mixins.json]. The plugin may be out of date: UnsupportedClassVersionError:dev/tonimatas/packetfixer/mixins/MixinConfigPlugin has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
java.lang.UnsupportedClassVersionError: dev/tonimatas/packetfixer/mixins/MixinConfigPlugin has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```

This was tested on a clean 1.20.1 NeoForge install with no other mods installed. [Logfile](https://github.com/TonimatasDEV/PacketFixer/files/15448142/latest.log).
I am running JRE 8u411 (latest).

**Comment by TonimatasDEV** [comment]
> (Mirrored from my entry on the Discord forum thread: "Fabric 1.20.1 instant crash")
> 
> The client crashes on launch with the following error:
> 
> ```
> [26May2024 10:42:30.882] [main/ERROR] [mixin/]: Error loading companion plugin class [dev.tonimatas.packetfixer.mixins.MixinConfigPlugin] for mixin config [packetfixer-common.mixins.json]. The plugin may be out of date: UnsupportedClassVersionError:dev/tonimatas/packetfixer/mixins/MixinConfigPlugin has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
> java.lang.UnsupportedClassVersionError: dev/tonimatas/packetfixer/mixins/MixinConfigPlugin has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
> ```
> 
> This was tested on a clean 1.20.1 NeoForge install with no other mods installed. [Logfile](https://github.com/TonimatasDEV/PacketFixer/files/15448142/latest.log). I am running JRE 8u411 (latest).

Redownload it
