### ISSUE TITLE
Question and possible bug in one

### ISSUE THREAD

**Issue by michiel1106** [TonimatasDEV/PacketFixer#40]
Is this mod able to work fully client side? I have it client side and when I pick up a shulker full of book bans, I dont get kicked which is good, but when I then open my inventory I do, or when I move it if I open a chest while its in my inventory. or when I open a book ban shulker while having one in my inventory too.

I think this could be fixed by making sure the inventory doesnt send less packages or something, honestly im not sure, but just like how dropping the item(the book ban shulker) and picking it up doesnt ban you, im hoping theres a way to have it not do that when opening your inventory. all client side hopefully.

**Comment by TonimatasDEV** [comment]
> Is this mod able to work fully client side? I have it client side and when I pick up a shulker full of book bans, I dont get kicked which is good, but when I then open my inventory I do, or when I move it if I open a chest while its in my inventory. or when I open a book ban shulker while having one in my inventory too.
> 
> I think this could be fixed by making sure the inventory doesnt send less packages or something, honestly im not sure, but just like how dropping the item(the book ban shulker) and picking it up doesnt ban you, im hoping theres a way to have it not do that when opening your inventory. all client side hopefully.

This mod is created for large modpacks (Client and Server side). Only increase the packet limit
