### ISSUE TITLE
Mod is unavailable on Third-party Launchers

### ISSUE THREAD

**Issue by DDriggs00** [TonimatasDEV/PacketFixer#41]
You have the Curseforge "Prevent Third-Party Distribution" setting enabled, which prevents your mod from being used on third-party launchers. Many people do not want to use the Overwolf launcher due to privacy and data-harvesting concerns, or inaccessibility on Linux, and this restriction makes it difficult for those people to use modpacks with your mod in them, as well as discouraging pack developers from including your mod. Additionally, it makes it much more difficult to host a server with this mod. For more details, see https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c

I'm assuming this is unintentional since your mod is under the MIT License and available on Modrinth.

**Comment by TonimatasDEV** [comment]
I forgot this option. Now you can!
