### ISSUE TITLE
”Unable to fit X into 3“ problem not fixed

### ISSUE THREAD

**Issue by AshdoII** [TonimatasDEV/PacketFixer#43]
mod version 1.4.0  game version 1.20.1  fabric version 0.15.11
still have the problem ”Unable to fit X into 3“ after adding this mod
had already disabled kyrpton and everycomp(good wood)
here are the log and modlist
[latest.log](https://github.com/user-attachments/files/15603602/latest.log)
https://drive.google.com/file/d/1bCg32KLakM8uParEE0vFaCZq4Q2ZCm4B/view?usp=drive_link, https://drive.google.com/file/d/15TAOSlsVc5uydd5q_hVfNW2eQnTLyUbN/view?usp=drive_link
mod pack is too big so I use google drive

**Comment by TonimatasDEV** [comment]
> mod version 1.4.0 game version 1.20.1 fabric version 0.15.11 still have the problem ”Unable to fit X into 3“ after adding this mod had already disabled kyrpton and everycomp(good wood) here are the log and modlist [latest.log](https://github.com/user-attachments/files/15603602/latest.log) https://drive.google.com/file/d/1bCg32KLakM8uParEE0vFaCZq4Q2ZCm4B/view?usp=drive_link, https://drive.google.com/file/d/15TAOSlsVc5uydd5q_hVfNW2eQnTLyUbN/view?usp=drive_link mod pack is too big so I use google drive

Test it: [packetfixer-fabric-1.4.1-1.19-to-1.20.1.zip](https://github.com/user-attachments/files/15749876/packetfixer-fabric-1.4.1-1.19-to-1.20.1.zip)

**Comment by AshdoII** [comment]
Start to have this strange error when I click [Mutiplayer].Here is the log file.
[2024-06-09-1.log](https://github.com/user-attachments/files/15750455/2024-06-09-1.log)
With this new version I cant find my server.

**Comment by TonimatasDEV** [comment]
> Start to have this strange error when I click [Mutiplayer].Here is the log file. [2024-06-09-1.log](https://github.com/user-attachments/files/15750455/2024-06-09-1.log) With this new version I cant find my server.

Delete krypton, it causes the problem

**Comment by AshdoII** [comment]
Solved after deleting kyrpton. Great thanks.
