### ISSUE TITLE
 There are issues when using velocity

### ISSUE THREAD

**Issue by MineYF** [TonimatasDEV/PacketFixer#44]
version 1.20.1 Fabric ,When I don't use velocity, the client can connect to the server normally, but when I use velocity, I get kicked out
 The feedback from the backend is as follows
[https://paste.fastmirror.net/?9c50393929bdac3e#GYBogGz3of1SCmg3i83FRD8sjuph6KSoHLcRH1Fo5Fmu](url)

**Comment by TonimatasDEV** [comment]
> version 1.20.1 Fabric ,When I don't use velocity, the client can connect to the server normally, but when I use velocity, I get kicked out The feedback from the backend is as follows [https://paste.fastmirror.net/?9c50393929bdac3e#GYBogGz3of1SCmg3i83FRD8sjuph6KSoHLcRH1Fo5Fmu](url)

Velocity + Mods is not good idea. I need to test it.

**Comment by TonimatasDEV** [comment]
Report it to Velocity. It works fine in normal Fabric/Forge.
