### ISSUE TITLE
The server crashed while I was loading this mod. 

### ISSUE THREAD

**Issue by SkyIce0229** [TonimatasDEV/PacketFixer#45]
This is the log information before the crash：
`[Server] WARNING: An illegal reflective access operation has occurred
[Server] WARNING: Illegal reflective access by net.minecraftforge.fml.common.ObfuscationReflectionHelper (modjar://forge) to method java.util.BitSet.trimToSize()
[Server] WARNING: Please consider reporting this to the maintainers of net.minecraftforge.fml.common.ObfuscationReflectionHelper
[Server] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[Server] WARNING: All illegal access operations will be denied in a future release
[Server] [21:49:55] [main/INFO] [minecraft/Bootstrap]: Vanilla bootstrap took 3581 milliseconds
[Server] [21:49:55] [main/WARN] [mixin/]: @ModifyConstant conflict. Skipping packetfixer-common.mixins.json:FriendlyByteBufMixin->@ModifyConstant::newSize(J)J with priority 1000, already redirected by randompatches.mixins.json:packetsizelimits.PacketBufferMixin->@ModifyConstant::getMaxNBTCompoundTagPacketSize(J)J with priority 1000
[Server] Exception in thread "main" [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:      at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:      at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:      at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:      at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:      at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:      at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:      at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:      at net.minecraftforge.server.ServerMain.main(ServerMain.java:43)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: Caused by: java.lang.reflect.InvocationTargetException
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]:      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]:      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]:      at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]:      at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]:      ... 7 more
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at net.minecraftforge.fml.network.NetworkInitialization.getHandshakeChannel(NetworkInitialization.java:27)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at net.minecraftforge.fml.network.FMLNetworkConstants.<clinit>(FMLNetworkConstants.java:35)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:115)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at net.minecraftforge.fml.ModLoader.get(ModLoader.java:140)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:30)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   at net.minecraft.server.Main.main(Main.java:95)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]:   ... 13 more
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method newSize(J)J in packetfixer-common.mixins.json:FriendlyByteBufMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap packetfixer-common-common-refmap.json
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]:   at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]:   at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]:   at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]:   at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]:   at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]:   at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]:   at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]:   at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[Server] [21:49:55] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]:   ... 29 more`

**Comment by TonimatasDEV** [comment]
> packetfixer-forge-1.4.1-1.16.5

Can you send the mod list/modpack?

**Comment by SkyIce0229** [comment]
Sure, I use [E6E](https://www.curseforge.com/minecraft/modpacks/enigmatica6expert/files/4915260) modPack, but if you need a list of mods I can send it to you.There is also the mod that I deleted the emoji inside, I hope it will not affect your error.
[manifest.json](https://github.com/user-attachments/files/16607543/manifest.json)
[modpack-download.zip](https://github.com/user-attachments/files/16607552/modpack-download.zip)

**Comment by TonimatasDEV** [comment]
Fixed in 1.4.2
