### ISSUE TITLE
Crash When Added To Pack

### ISSUE THREAD

**Issue by N-Montana** [TonimatasDEV/PacketFixer#46]
Trying to add this to my edit of Vault Hunters 3 to resolve some issues with people joining my server but get this error almost immediately after trying to start the game https://pastebin.com/QcKzZ12k

If you want to take a look at the pack yourself it's this https://drive.google.com/file/d/1F3XUQlrH9Syc-ZjH4j4KL09zB-_sVDe1/view?usp=drive_link but adding Packet Fixer.

Using the latest forge for 1.18.2 (40.2.21), and version 1.4.2 of Packet Fixer.

Any help would be appreciated.

**Comment by TonimatasDEV** [comment]
Fixed in the version 1.4.3 of Packet Fixer

**Comment by N-Montana** [comment]
Thank you so much!
