### ISSUE TITLE
[1.12.2]Crash When Added To ModPack

### ISSUE THREAD

**Issue by ElinM-Challenge** [TonimatasDEV/PacketFixer#49]
When added to modpcak and launch minecraft, the game crash immediately, the crash report are as follows:

[crash-2024-11-03_01.37.59-client.txt](https://github.com/user-attachments/files/17607817/crash-2024-11-03_01.37.59-client.txt)

Grateful for your assistance with my question!  :)

**Comment by TonimatasDEV** [comment]
It is a problem with RandomPatches. I will mention you when I release the new version with it fixed.

**Comment by TonimatasDEV** [comment]
@ElinM-Challenge Fixed in 1.12.2-1.0.1

**Comment by ElinM-Challenge** [comment]
Deeply grateful for your help!  :)
