### ISSUE TITLE
1.12.2 server crash

### ISSUE THREAD

**Issue by IdkWhatNameThingyToPut** [TonimatasDEV/PacketFixer#50]
Hello my server seems to crash when it's installed on the server

Latest.log:
[latest (6).log](https://github.com/user-attachments/files/17638247/latest.6.log)

Crashlog:
[crash-2024-11-05_20.23.24-server.txt](https://github.com/user-attachments/files/17638250/crash-2024-11-05_20.23.24-server.txt)

I'm thinking this is a problem with mixins? I think it mentions galacticcraft on the crash report but I'm just going to say right now that my modpack works completely fine until packet fixer is installed only then does a crash happen. So maybe this is a mod incompatibility with galacticcraft or in general mixin incompatibility type stuff? Not sure anyway hope you can get this fixed.

**Comment by TonimatasDEV** [comment]
I'm fixing it

**Comment by TonimatasDEV** [comment]
@IdkWhatNameThingyToPut Download the latest version 1.0.2: https://modrinth.com/mod/packet-fixer

**Comment by IdkWhatNameThingyToPut** [comment]
> @IdkWhatNameThingyToPut Fixed in the latest version 1.0.2: https://modrinth.com/mod/packet-fixer

Thank you very much please put this on CurseForge too if you haven't done that already

**Comment by TonimatasDEV** [comment]
@IdkWhatNameThingyToPut Now it is

**Comment by IdkWhatNameThingyToPut** [comment]
> @IdkWhatNameThingyToPut Now it is

Downloaded the new version from curseforge and it seems to be working good now, thanks
