### ISSUE TITLE
MOD doesn't work

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [TonimatasDEV/PacketFixer#51]
![屏幕截图 2024-11-15 215245](https://github.com/user-attachments/assets/29de6898-c4cd-4cb5-81ec-89051f43ba6a)
![屏幕截图 2024-11-15 221025](https://github.com/user-attachments/assets/daffa28a-9ac4-4f95-8e10-d93ee89ab228)
![屏幕截图 2024-11-15 221147](https://github.com/user-attachments/assets/6e9a4d7b-9649-4fca-98a1-fcb92e865261)
![屏幕截图 2024-11-15 221221](https://github.com/user-attachments/assets/9fdf7a94-60d0-48be-829a-a2f4b92f7e7f)

**Comment by TonimatasDEV** [comment]
@MinecraftEarthVillage You need the mod in server and client side
